# SQLAlchemy Core e ORM — Loja Brasil


A base Loja Brasil possui os schemas `cadastro`, `vendas`, `compras`, `estoque`, `producao`, `rh` e `financeiro`. Os exemplos abaixo usam principalmente clientes, produtos, categorias, pedidos e itens de pedido.

**Objetivos**
- Conectar Python ao PostgreSQL.
- Entender SQLAlchemy Core x ORM.
- Fazer SELECT, INSERT, UPDATE e DELETE.
- Criar uma tabela de teste.
- Trabalhar com transações e rollback.
- Fazer JOINs, agregações e cálculos.
- Integrar SQLAlchemy com Pandas.
- Resolver exercícios.

## 1. Instalação

```bash
pip install sqlalchemy psycopg2-binary pandas
```

In [1]:
from sqlalchemy import (
    create_engine, MetaData, Column, Integer, String,
    Numeric, Boolean, ForeignKey, select, insert, update,
    delete, func, and_, or_, text
)
from sqlalchemy.orm import DeclarativeBase, Session, relationship
import pandas as pd

In [2]:
DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/loja_brasil"

engine = create_engine(DATABASE_URL, echo=False)

with engine.connect() as conn:
    print(conn.execute(text("SELECT version();")).scalar())

PostgreSQL 18.3 on x86_64-windows, compiled by msvc-19.44.35225, 64-bit

# Parte I — SQLAlchemy Core

No Core trabalhamos diretamente com `Table`, `Column` e expressões SQL.

In [3]:
metadata = MetaData()

for schema in ["cadastro", "vendas"]:
    metadata.reflect(bind=engine, schema=schema)

print(metadata.tables.keys())

dict_keys(['cadastro.categorias', 'cadastro.produtos', 'cadastro.marcas', 'cadastro.clientes', 'cadastro.fornecedores', 'vendas.pedidos', 'rh.funcionarios', 'rh.cargos', 'rh.departamentos', 'vendas.itens_pedido', 'vendas.pagamentos'])

In [4]:
clientes = metadata.tables["cadastro.clientes"]
categorias = metadata.tables["cadastro.categorias"]
marcas = metadata.tables["cadastro.marcas"]
produtos = metadata.tables["cadastro.produtos"]
pedidos = metadata.tables["vendas.pedidos"]
itens_pedido = metadata.tables["vendas.itens_pedido"]
pagamentos = metadata.tables["vendas.pagamentos"]
fornecedores = metadata.tables["cadastro.fornecedores"]

## 2. SELECT simples

In [5]:
stmt = select(clientes)

with engine.connect() as conn:
    for linha in conn.execute(stmt).fetchmany(10):
        print(linha)

(2, 'Bruno Henrique Souza', 'bruno.souza@email.com', 'Pomerode', 'SC', datetime.date(2025, 1, 16), True)
(3, 'Camila Rodrigues', 'camila.rodrigues@email.com', 'Joinville', 'SC', datetime.date(2025, 1, 27), True)
(4, 'Daniel Oliveira', 'daniel.oliveira@email.com', 'Itajaí', 'SC', datetime.date(2025, 2, 7), True)
(5, 'Eduarda Fernandes', 'eduarda.fernandes@email.com', 'Florianópolis', 'SC', datetime.date(2025, 2, 18), True)
(6, 'Felipe Almeida', 'felipe.almeida@email.com', 'Brusque', 'SC', datetime.date(2025, 3, 1), True)
(7, 'Gabriela Costa', 'gabriela.costa@email.com', 'Blumenau', 'SC', datetime.date(2025, 3, 12), True)
(8, 'Henrique Martins', 'henrique.martins@email.com', 'Jaraguá do Sul', 'SC', datetime.date(2025, 3, 23), True)
(9, 'Isabela Santos', 'isabela.santos@email.com', 'Rio do Sul', 'SC', datetime.date(2025, 4, 3), True)
(10, 'João Pedro Lima', 'joao.lima@email.com', 'Timbó', 'SC', datetime.date(2025, 4, 14), True)
(11, 'Karina Souza', 'karina.souza@email.com', 'Gaspar', 'SC', datetime.date(2025, 4, 25), True)

## 3. Selecionando colunas

In [6]:
stmt = select(
    clientes.c.id_cliente,
    clientes.c.nome,
    clientes.c.cidade,
    clientes.c.estado
)

with engine.connect() as conn:
    for linha in conn.execute(stmt).fetchmany(10):
        print(linha)

(2, 'Bruno Henrique Souza', 'Pomerode', 'SC')
(3, 'Camila Rodrigues', 'Joinville', 'SC')
(4, 'Daniel Oliveira', 'Itajaí', 'SC')
(5, 'Eduarda Fernandes', 'Florianópolis', 'SC')
(6, 'Felipe Almeida', 'Brusque', 'SC')
(7, 'Gabriela Costa', 'Blumenau', 'SC')
(8, 'Henrique Martins', 'Jaraguá do Sul', 'SC')
(9, 'Isabela Santos', 'Rio do Sul', 'SC')
(10, 'João Pedro Lima', 'Timbó', 'SC')
(11, 'Karina Souza', 'Gaspar', 'SC')

## 4. WHERE

In [7]:
stmt = (
    select(clientes.c.nome, clientes.c.cidade)
    .where(clientes.c.cidade == "Blumenau")
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

('Gabriela Costa', 'Blumenau')
('Mariana Alves', 'Blumenau')
('Patrícia Mendes', 'Blumenau')
('Cliente Teste', 'Blumenau')

## 5. AND e OR

In [8]:
stmt = (
    select(clientes.c.nome, clientes.c.cidade)
    .where(
        and_(
            clientes.c.estado == "SC",
            clientes.c.ativo == True
        )
    )
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

('Bruno Henrique Souza', 'Pomerode')
('Camila Rodrigues', 'Joinville')
('Daniel Oliveira', 'Itajaí')
('Eduarda Fernandes', 'Florianópolis')
('Felipe Almeida', 'Brusque')
('Gabriela Costa', 'Blumenau')
('Henrique Martins', 'Jaraguá do Sul')
('Isabela Santos', 'Rio do Sul')
('João Pedro Lima', 'Timbó')
('Karina Souza', 'Gaspar')
('Lucas Pereira', 'Indaial')
('Mariana Alves', 'Blumenau')
('Natália Rocha', 'São José')
('Otávio Ribeiro', 'Chapecó')
('Patrícia Mendes', 'Blumenau')
('Rafael Gomes', 'Pomerode')
('Sabrina Teixeira', 'Itajaí')
('Thiago Nunes', 'Balneário Camboriú')
('Vanessa Cardoso', 'Brusque')
('Ana Paula Martins', 'Florianópolis')
('Cliente Teste', 'Blumenau')
('Cliente Pandas', 'Itajaí')
('Ana Souza', 'Pomerode')
('Carlos Lima', 'Joinville')

In [9]:
stmt = (
    select(clientes.c.nome, clientes.c.cidade)
    .where(
        or_(
            clientes.c.cidade == "Blumenau",
            clientes.c.cidade == "Pomerode"
        )
    )
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

('Bruno Henrique Souza', 'Pomerode')
('Gabriela Costa', 'Blumenau')
('Mariana Alves', 'Blumenau')
('Patrícia Mendes', 'Blumenau')
('Rafael Gomes', 'Pomerode')
('Cliente Teste', 'Blumenau')
('Ana Souza', 'Pomerode')

## 6. ORDER BY + LIMIT — 5 produtos mais caros

In [10]:
stmt = (
    select(produtos.c.nome, produtos.c.preco_venda)
    .order_by(produtos.c.preco_venda.desc())
    .limit(5)
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

('Tênis Esportivo', Decimal('279.90'))
('Jaqueta Corta-Vento', Decimal('249.90'))
('Jaqueta Jeans', Decimal('219.90'))
('Tênis Casual Branco', Decimal('199.90'))
('Vestido Midi Floral', Decimal('189.90'))

## 7. COUNT, AVG e GROUP BY

In [11]:
stmt = select(func.count(clientes.c.id_cliente))

with engine.connect() as conn:
    print("Clientes:", conn.scalar(stmt))

Clientes: 24

In [12]:
stmt = select(func.avg(produtos.c.preco_venda))

with engine.connect() as conn:
    print("Preço médio:", conn.scalar(stmt))

Preço médio: 132.9555555555555556

In [13]:
stmt = (
    select(
        clientes.c.cidade,
        func.count(clientes.c.id_cliente).label("quantidade")
    )
    .group_by(clientes.c.cidade)
    .order_by(func.count(clientes.c.id_cliente).desc())
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

('Blumenau', 4)
('Itajaí', 3)
('Pomerode', 3)
('Florianópolis', 2)
('Brusque', 2)
('Joinville', 2)
('Timbó', 1)
('São José', 1)
('Jaraguá do Sul', 1)
('Chapecó', 1)
('Indaial', 1)
('Gaspar', 1)
('Balneário Camboriú', 1)
('Rio do Sul', 1)

## 8. HAVING — cidades com pelo menos 3 clientes

In [14]:
stmt = (
    select(
        clientes.c.cidade,
        func.count(clientes.c.id_cliente).label("quantidade")
    )
    .group_by(clientes.c.cidade)
    .having(func.count(clientes.c.id_cliente) >= 3)
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

('Blumenau', 4)
('Pomerode', 3)
('Itajaí', 3)

## 9. JOIN — cliente + pedido

In [15]:
stmt = (
    select(
        clientes.c.nome.label("cliente"),
        pedidos.c.id_pedido,
        pedidos.c.data_pedido,
        pedidos.c.status
    )
    .join(
        pedidos,
        clientes.c.id_cliente == pedidos.c.id_cliente
    )
)

with engine.connect() as conn:
    for linha in conn.execute(stmt).fetchmany(10):
        print(linha)

('Henrique Martins', 1, datetime.date(2025, 2, 10), 'Pendente')
('Otávio Ribeiro', 2, datetime.date(2025, 2, 19), 'Entregue')
('Bruno Henrique Souza', 3, datetime.date(2025, 2, 28), 'Enviado')
('Isabela Santos', 4, datetime.date(2025, 3, 9), 'Cancelado')
('Patrícia Mendes', 5, datetime.date(2025, 3, 18), 'Entregue')
('Camila Rodrigues', 6, datetime.date(2025, 3, 27), 'Entregue')
('João Pedro Lima', 7, datetime.date(2025, 4, 5), 'Pago')
('Rafael Gomes', 8, datetime.date(2025, 4, 14), 'Pendente')
('Daniel Oliveira', 9, datetime.date(2025, 4, 23), 'Entregue')
('Karina Souza', 10, datetime.date(2025, 5, 2), 'Enviado')

## 10. LEFT JOIN

In [16]:
stmt = (
    select(
        clientes.c.nome.label("cliente"),
        pedidos.c.id_pedido
    )
    .outerjoin(
        pedidos,
        clientes.c.id_cliente == pedidos.c.id_cliente
    )
)

with engine.connect() as conn:
    for linha in conn.execute(stmt).fetchmany(10):
        print(linha)

('Henrique Martins', 1)
('Otávio Ribeiro', 2)
('Bruno Henrique Souza', 3)
('Isabela Santos', 4)
('Patrícia Mendes', 5)
('Camila Rodrigues', 6)
('João Pedro Lima', 7)
('Rafael Gomes', 8)
('Daniel Oliveira', 9)
('Karina Souza', 10)

## 11. JOIN de várias tabelas

In [17]:
stmt = (
    select(
        pedidos.c.id_pedido,
        clientes.c.nome.label("cliente"),
        produtos.c.nome.label("produto"),
        itens_pedido.c.quantidade,
        itens_pedido.c.preco_unitario
    )
    .join(clientes, clientes.c.id_cliente == pedidos.c.id_cliente)
    .join(itens_pedido, itens_pedido.c.id_pedido == pedidos.c.id_pedido)
    .join(produtos, produtos.c.id_produto == itens_pedido.c.id_produto)
)

with engine.connect() as conn:
    for linha in conn.execute(stmt).fetchmany(10):
        print(linha)

(1, 'Henrique Martins', 'Calça Mom Feminina', 2, Decimal('159.90'))
(1, 'Henrique Martins', 'Cinto de Couro', 3, Decimal('79.90'))
(1, 'Henrique Martins', 'Camiseta Polo Masculina', 4, Decimal('89.90'))
(2, 'Otávio Ribeiro', 'Tênis Casual Branco', 3, Decimal('199.90'))
(2, 'Otávio Ribeiro', 'Cachecol Tricot', 4, Decimal('54.90'))
(2, 'Otávio Ribeiro', 'Vestido Midi Floral', 1, Decimal('189.90'))
(2, 'Otávio Ribeiro', 'Bolsa Transversal', 2, Decimal('169.90'))
(3, 'Bruno Henrique Souza', 'Carteira Masculina', 4, Decimal('69.90'))
(3, 'Bruno Henrique Souza', 'Calça Sarja Masculina', 1, Decimal('139.90'))
(4, 'Isabela Santos', 'Camiseta Cropped Feminina', 1, Decimal('69.90'))

## 12. Cálculo do valor do item

In [18]:
valor_item = (
    itens_pedido.c.quantidade
    * itens_pedido.c.preco_unitario
    * (1 - itens_pedido.c.desconto / 100)
)

#valor_item_arredondado = func.round(valor_item, 2)

stmt = select(
    itens_pedido.c.id_item,
    valor_item.label("valor_total")
)

with engine.connect() as conn:
    for linha in conn.execute(stmt).fetchmany(10):
        print(linha)

(1, Decimal('319.8000000000000000000000'))
(2, Decimal('227.7150000000000000000000'))
(3, Decimal('323.6400000000000000000000'))
(4, Decimal('569.7150000000000000000000'))
(5, Decimal('197.6400000000000000000000'))
(6, Decimal('189.9000000000000000000000'))
(7, Decimal('339.8000000000000000000000'))
(8, Decimal('251.6400000000000000000000'))
(9, Decimal('139.9000000000000000000000'))
(10, Decimal('69.9000000000000000000000'))

## 13. Faturamento por produto

In [19]:
stmt = (
    select(
        produtos.c.nome.label("produto"),
        func.round(func.sum(valor_item),2).label("faturamento")
    )
    .join(
        itens_pedido,
        produtos.c.id_produto == itens_pedido.c.id_produto
    )
    .group_by(produtos.c.nome)
    .order_by(func.round(func.sum(valor_item),2).desc())
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

('Jaqueta Corta-Vento', Decimal('6997.20'))
('Bolsa Transversal', Decimal('5776.60'))
('Vestido Curto Casual', Decimal('5040.12'))
('Tênis Casual Branco', Decimal('5017.49'))
('Calça Jeans Slim', Decimal('4437.04'))
('Tênis Esportivo', Decimal('4254.48'))
('Calça Sarja Masculina', Decimal('3630.41'))
('Camiseta Polo Masculina', Decimal('3524.08'))
('Vestido Midi Floral', Decimal('3304.26'))
('Calça Mom Feminina', Decimal('3261.96'))
('Jaqueta Jeans', Decimal('2133.03'))
('Carteira Masculina', Decimal('1845.36'))
('Cinto de Couro', Decimal('1617.98'))
('Camiseta Básica Algodão', Decimal('1203.99'))
('Cachecol Tricot', Decimal('1119.96'))
('Camiseta Cropped Feminina', Decimal('1006.56'))
('Meia Esportiva', Decimal('775.91'))
('Boné Casual', Decimal('718.56'))

# Parte II — Criando uma tabela de teste

Vamos criar `cadastro.teste_sqlalchemy`. Ela é independente das tabelas de negócio e será usada para praticar CRUD, ORM e transações.

In [20]:
with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS cadastro.teste"))
    conn.execute(text(
        "CREATE TABLE cadastro.teste ("
        "id_teste INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, "
        "nome VARCHAR(100) NOT NULL, "
        "cidade VARCHAR(80), "
        "valor NUMERIC(10,2), "
        "ativo BOOLEAN DEFAULT TRUE)"
    ))

print("Tabela criada.")

Tabela criada.

In [21]:
metadata.reflect(bind=engine, schema="cadastro")

tabela_teste = metadata.tables["cadastro.teste"]

## 14. INSERT — Core

In [22]:
stmt = insert(tabela_teste).values(
    nome="Teste Core",
    cidade="Blumenau",
    valor=99.90,
    ativo=True
)

with engine.begin() as conn:
    resultado = conn.execute(stmt)

print("Inseridos:", resultado.rowcount)

Inseridos: 1

## 15. INSERT de vários registros

In [23]:
dados = [
    {"nome": "Teste 1", "cidade": "Blumenau", "valor": 100, "ativo": True},
    {"nome": "Teste 2", "cidade": "Pomerode", "valor": 200, "ativo": True},
    {"nome": "Teste 3", "cidade": "Joinville", "valor": 300, "ativo": False},
]

with engine.begin() as conn:
    conn.execute(insert(tabela_teste), dados)

In [25]:
stmt = select(tabela_teste)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

(1, 'Teste Core', 'Blumenau', Decimal('99.90'), True)
(2, 'Teste 1', 'Blumenau', Decimal('100.00'), True)
(3, 'Teste 2', 'Pomerode', Decimal('200.00'), True)
(4, 'Teste 3', 'Joinville', Decimal('300.00'), False)

## 16. UPDATE — Core

In [26]:
stmt = (
    update(tabela_teste)
    .where(tabela_teste.c.nome == "Teste 1")
    .values(valor=150)
)

with engine.begin() as conn:
    resultado = conn.execute(stmt)

print("Atualizados:", resultado.rowcount)

Atualizados: 1

## 17. DELETE — Core

In [27]:
stmt = (
    delete(tabela_teste)
    .where(tabela_teste.c.nome == "Teste 3")
)

with engine.begin() as conn:
    resultado = conn.execute(stmt)

print("Excluídos:", resultado.rowcount)

Excluídos: 1

# Parte III — Transações

`commit()` confirma alterações. `rollback()` desfaz alterações ainda não confirmadas.

In [28]:
with engine.connect() as conn:
    transacao = conn.begin()

    conn.execute(
        insert(tabela_teste).values(
            nome="Registro Rollback",
            cidade="Blumenau",
            valor=999.99
        )
    )

    print("Registro inserido dentro da transação.")

    transacao.rollback()
    print("Rollback executado.")

Registro inserido dentro da transação.
Rollback executado.

In [29]:
stmt = select(tabela_teste).where(
    tabela_teste.c.nome == "Registro Rollback"
)

with engine.connect() as conn:
    print("Resultado:", conn.execute(stmt).all())

Resultado: []

# Parte IV — SQLAlchemy ORM

In [30]:
class Base(DeclarativeBase):
    pass

## 18. Modelo ORM para a tabela de teste

In [31]:
class TesteSQLAlchemy(Base):

    __tablename__ = "teste_sqlalchemy"
    __table_args__ = {"schema": "cadastro"}

    id_teste = Column(Integer, primary_key=True)
    nome = Column(String(100), nullable=False)
    cidade = Column(String(80))
    valor = Column(Numeric(10, 2))
    ativo = Column(Boolean, default=True)

    def __repr__(self):
        return (
            f"<TesteSQLAlchemy("
            f"id={self.id_teste}, "
            f"nome='{self.nome}', "
            f"valor={self.valor})>"
        )

Base.metadata.create_all(engine)
print("Tabela criada ou já existente.")

Tabela criada ou já existente.

## 19. SELECT com ORM

In [33]:
stmt = select(TesteSQLAlchemy)

with Session(engine) as session:
    registros = session.scalars(stmt).all()

    for registro in registros:
        print(registro)

## 20. `scalars()` x `execute()`

In [34]:
stmt = select(TesteSQLAlchemy.nome)

with Session(engine) as session:
    nomes = session.scalars(stmt).all()

print(nomes)

[]

In [35]:
stmt = select(
    TesteSQLAlchemy.nome,
    TesteSQLAlchemy.cidade
)

with Session(engine) as session:
    resultado = session.execute(stmt)

    for linha in resultado:
        print(linha.nome, linha.cidade)

## 21. WHERE com ORM

In [ ]:
stmt = (
    select(TesteSQLAlchemy)
    .where(TesteSQLAlchemy.valor > 100)
)

with Session(engine) as session:
    for registro in session.scalars(stmt):
        print(registro)

## 22. INSERT com ORM

In [36]:
novo = TesteSQLAlchemy(
    nome="Cliente ORM",
    cidade="Blumenau",
    valor=450,
    ativo=True
)

with Session(engine) as session:
    session.add(novo)
    session.commit()

    print("ID gerado:", novo.id_teste)

ID gerado: 1

## 23. INSERT de vários objetos

In [37]:
registros = [
    TesteSQLAlchemy(nome="ORM 1", cidade="Blumenau", valor=120),
    TesteSQLAlchemy(nome="ORM 2", cidade="Pomerode", valor=250),
    TesteSQLAlchemy(nome="ORM 3", cidade="Timbó", valor=320),
]

with Session(engine) as session:
    session.add_all(registros)
    session.commit()

## 24. UPDATE com ORM

In [38]:
with Session(engine) as session:
    registro = session.get(TesteSQLAlchemy, 1)

    if registro:
        registro.valor = 999.99
        session.commit()
        print(registro)

<TesteSQLAlchemy(id=1, nome='Cliente ORM', valor=999.99)>

## 25. DELETE com ORM

In [39]:
with Session(engine) as session:
    registro = session.get(TesteSQLAlchemy, 3)

    if registro:
        session.delete(registro)
        session.commit()
        print("Registro excluído.")

Registro excluído.

# Parte VI — SQLAlchemy + Pandas

In [40]:
stmt = (
    select(
        produtos.c.nome,
        produtos.c.preco_venda
    )
    .order_by(produtos.c.preco_venda.desc())
)

with engine.connect() as conn:
    df = pd.read_sql(stmt, conn)

df.head()

                  nome  preco_venda
0      Tênis Esportivo        279.9
1  Jaqueta Corta-Vento        249.9
2        Jaqueta Jeans        219.9
3  Tênis Casual Branco        199.9
4  Vestido Midi Floral        189.9

## 26. Relatório de pedidos

In [41]:
stmt = (
    select(
        clientes.c.nome.label("cliente"),
        clientes.c.cidade,
        pedidos.c.id_pedido,
        pedidos.c.data_pedido,
        pedidos.c.status
    )
    .join(
        pedidos,
        clientes.c.id_cliente == pedidos.c.id_cliente
    )
)

with engine.connect() as conn:
    df_pedidos = pd.read_sql(stmt, conn)

df_pedidos.head(10)

                cliente          cidade  id_pedido data_pedido     status
0      Henrique Martins  Jaraguá do Sul          1  2025-02-10   Pendente
1        Otávio Ribeiro         Chapecó          2  2025-02-19   Entregue
2  Bruno Henrique Souza        Pomerode          3  2025-02-28    Enviado
3        Isabela Santos      Rio do Sul          4  2025-03-09  Cancelado
4       Patrícia Mendes        Blumenau          5  2025-03-18   Entregue
5      Camila Rodrigues       Joinville          6  2025-03-27   Entregue
6       João Pedro Lima           Timbó          7  2025-04-05       Pago
7          Rafael Gomes        Pomerode          8  2025-04-14   Pendente
8       Daniel Oliveira          Itajaí          9  2025-04-23   Entregue
9          Karina Souza          Gaspar         10  2025-05-02    Enviado

## 27. Relatório detalhado de vendas

In [42]:
stmt = (
    select(
        clientes.c.nome.label("cliente"),
        pedidos.c.id_pedido,
        pedidos.c.data_pedido,
        pedidos.c.status,
        produtos.c.nome.label("produto"),
        itens_pedido.c.quantidade,
        itens_pedido.c.preco_unitario,
        itens_pedido.c.desconto,
        valor_item.label("valor_item")
    )
    .join(
        pedidos,
        clientes.c.id_cliente == pedidos.c.id_cliente
    )
    .join(
        itens_pedido,
        pedidos.c.id_pedido == itens_pedido.c.id_pedido
    )
    .join(
        produtos,
        itens_pedido.c.id_produto == produtos.c.id_produto
    )
)


with engine.connect() as conn:
    df_vendas = pd.read_sql(stmt, conn)

df_vendas.head(10)

,cliente,id_pedido,data_pedido,status,produto,quantidade,preco_unitario,desconto,valor_item
0,Henrique Martins,1,2025-02-10,Pendente,Calça Mom Feminina,2,159.9,0.0,319.800
1,Henrique Martins,1,2025-02-10,Pendente,Cinto de Couro,3,79.9,5.0,227.715
2,Henrique Martins,1,2025-02-10,Pendente,Camiseta Polo Masculina,4,89.9,10.0,323.640
3,Otávio Ribeiro,2,2025-02-19,Entregue,Tênis Casual Branco,3,199.9,5.0,569.715
4,Otávio Ribeiro,2,2025-02-19,Entregue,Cachecol Tricot,4,54.9,10.0,197.640
5,Otávio Ribeiro,2,2025-02-19,Entregue,Vestido Midi Floral,1,189.9,0.0,189.900
6,Otávio Ribeiro,2,2025-02-19,Entregue,Bolsa Transversal,2,169.9,0.0,339.800
7,Bruno Henrique Souza,3,2025-02-28,Enviado,Carteira Masculina,4,69.9,10.0,251.640
8,Bruno Henrique Souza,3,2025-02-28,Enviado,Calça Sarja Masculina,1,139.9,0.0,139.900
9,Isabela Santos,4,2025-03-09,Cancelado,Camiseta Cropped Feminina,1,69.9,0.0,69.900

In [43]:
df_vendas.groupby(
    "produto"
)["valor_item"].sum().sort_values(
    ascending=False
).head(10)

produto
Jaqueta Corta-Vento        6997.200
Bolsa Transversal          5776.600
Vestido Curto Casual       5040.120
Tênis Casual Branco        5017.490
Calça Jeans Slim           4437.040
Tênis Esportivo            4254.480
Calça Sarja Masculina      3630.405
Camiseta Polo Masculina    3524.080
Vestido Midi Floral        3304.260
Calça Mom Feminina         3261.960
Name: valor_item, dtype: float64

# Exercícios

**1. Core:** liste clientes ativos mostrando nome, cidade e estado.

**2. Core:** liste produtos com preço menor que R$ 100,00, do mais barato para o mais caro.

**3. Core:** mostre os 10 produtos mais caros.

**4. Core:** calcule a quantidade de clientes por cidade e ordene de forma decrescente.

**5. Core:** faça JOIN entre produtos e categorias e mostre produto, categoria e preço.

**6. Pandas:** crie um DataFrame com cliente, cidade, pedido, data e status.

**7. Relatório:** crie um DataFrame com cliente, pedido, produto, quantidade, preço, desconto e valor do item.

**8. Faturamento:** calcule o faturamento total por produto usando quantidade, preço e desconto.

**9. Desafio final:** crie um relatório por cliente contendo quantidade de pedidos, quantidade de itens e faturamento total.

# Gabaritos

## Gabarito 1

In [ ]:
stmt = (
    select(
        clientes.c.nome,
        clientes.c.cidade,
        clientes.c.estado
    )
    .where(clientes.c.ativo == True)
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

## Gabarito 2

In [ ]:
stmt = (
    select(produtos.c.nome, produtos.c.preco_venda)
    .where(produtos.c.preco_venda < 100)
    .order_by(produtos.c.preco_venda)
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

## Gabarito 4

In [ ]:
stmt = (
    select(
        clientes.c.cidade,
        func.count(clientes.c.id_cliente).label("quantidade")
    )
    .group_by(clientes.c.cidade)
    .order_by(func.count(clientes.c.id_cliente).desc())
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

## Gabarito 5

In [ ]:
stmt = (
    select(
        produtos.c.nome.label("produto"),
        categorias.c.nome.label("categoria"),
        produtos.c.preco_venda
    )
    .join(
        categorias,
        produtos.c.id_categoria == categorias.c.id_categoria
    )
)

with engine.connect() as conn:
    for linha in conn.execute(stmt):
        print(linha)

# Resumo final

### Core
`Table → Column → SQL → PostgreSQL`

### ORM
`Classe → Objeto → SQL → PostgreSQL`

### Transações
`BEGIN → INSERT/UPDATE/DELETE → COMMIT ou ROLLBACK`

### Integração
`PostgreSQL → SQLAlchemy → Pandas → Análise/BI`

Os dois estilos podem coexistir no mesmo projeto. Core é especialmente confortável para consultas e ETL; ORM é especialmente útil quando entidades e relacionamentos são representados como objetos Python.